### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by AparnaManjalavil** [mesibo/messenger-app-android-kotlin#5]
I had use new call api 1.2.26. After change the compileSDKversion 28 to 29  app is crashed.
It shows the error as follows:-
 java.lang.SecurityException: Permission Denial: opening provider com.android.providers.contacts.ContactsProvider2 from ProcessRecord{edbe3b4 2606:org.mesibo.messenger/u0a925} (pid=2606, uid=10925) requires android.permission.READ_CONTACTS or android.permission.WRITE_CONTACTS.
at android.os.Parcel.createException(Parcel.java:2087)
 at android.os.Parcel.createException(Parcel.java:2087)
        at android.os.Parcel.readException(Parcel.java:2055)
        at android.os.Parcel.readException(Parcel.java:2003)
        at android.content.IContentService$Stub$Proxy.registerContentObserver(IContentService.java:1234)
        at android.content.ContentResolver.registerContentObserver(ContentResolver.java:2404)
        at android.content.ContentResolver.registerContentObserver(ContentResolver.java:2392)
        at com.mesibo.contactutils.c.a(SourceFile:141)
        at com.mesibo.contactutils.ContactUtils.sync(SourceFile:50)
        at org.mesibo.messenger.SampleAPI.startContactsSync(SampleAPI.kt:388)
        at org.mesibo.messenger.SampleAPI.parseResponse(SampleAPI.kt:231)
        at org.mesibo.messenger.SampleAPI.access$parseResponse(SampleAPI.kt:67)
        at org.mesibo.messenger.SampleAPI$ResponseHandler.Mesibo_onHttpProgress(SampleAPI.kt:798)
        at com.mesibo.api.h$1.handleMessage(SourceFile:77)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7840)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:985)
How to solve this problem.

**Comment by mesibo** [comment]
What steps you have taken to resolve this issue?

**Comment by AparnaManjalavil** [comment]
I add the permission for write contacts.
<uses-permission android:name="android.permission.WRITE_CONTACTS"/>But it failed

**Comment by mesibo** [comment]
Read https://mesibo.com/documentation/faq/support/#can-you-help-with-messenger-whatsapp-clone-demo 

Although we can help with mesibo related issues, we do expect you to debug and resolve system related issues yourself (for example contact permissions).

**Comment by AparnaManjalavil** [comment]
I am finding this issue in messanger whatsapp clone demo.
